version: '3'
services:
  fastapi_lambda_service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRESQL_DATABASE_URL=${POSTGRESQL_DATABASE_URL}
    env_file:
      - .env
    ports:
      - "9000:8080"
